name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  tests:
    name: Run tests and quality checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies (Lean toolchain)
        run: |
          curl -sSf https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- --default-toolchain leanprover/lean4:4.17.0-rc1 -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: Show versions
        run: |
          elan --version
          lean --version
          lake --version
      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.10
      - name: Build repl
        run: |
          cd repl/ && lake exe cache get && lake build
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[tests]"
      - name: Run tests
        run: |
          make test

